<?php

namespace Database\Seeders;

use App\Models\PointCatalogItem;
use Illuminate\Database\Seeder;

class PointCatalogItemSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pointCatalogItems = [
            // コンサルティング系
            [
                'name' => 'オンライン相談30分',
                'points_cost' => 300,
                'description' => '通常サポート',
                'is_active' => true,
                'sort_order' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'オンライン相談60分',
                'points_cost' => 500,
                'description' => '通常サポート',
                'is_active' => true,
                'sort_order' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'サイト改善アドバイス',
                'points_cost' => 800,
                'description' => 'webサイトの改善点をアドバイスいたします。',
                'is_active' => true,
                'sort_order' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'マーケティング相談',
                'points_cost' => 1000,
                'description' => 'マーケティングに関するご相談を承ります。',
                'is_active' => true,
                'sort_order' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'アクセス解析レポート解説',
                'points_cost' => 1500,
                'description' => 'アクセス解析レポートの内容を解説いたします。',
                'is_active' => true,
                'sort_order' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // webサイト診断
            [
                'name' => 'SEO簡易診断',
                'points_cost' => 500,
                'description' => '現在のサイトのSEO状況を簡易診断いたします。',
                'is_active' => true,
                'sort_order' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '表示速度診断',
                'points_cost' => 800,
                'description' => '現在のサイトの表示速度を診断いたします。',
                'is_active' => true,
                'sort_order' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'セキュリティ診断',
                'points_cost' => 1000,
                'description' => '現在のサイトのセキュリティ状況を診断いたします。',
                'is_active' => true,
                'sort_order' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'UI/UX診断',
                'points_cost' => 1200,
                'description' => '現在のサイトのUI/UXを診断いたします。',
                'is_active' => true,
                'sort_order' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '総合Webサイト診断',
                'points_cost' => 1500,
                'description' => '現在のサイトの総合的な状況を診断いたします。',
                'is_active' => true,
                'sort_order' => 10,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // コンテンツ制作
            [
                'name' => 'ブログ記事テーマ提案',
                'points_cost' => 500,
                'description' => 'ブログ記事のテーマを提案いたします。',
                'is_active' => true,
                'sort_order' => 11,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ブログ記事1本添削',
                'points_cost' => 1000,
                'description' => 'ブログ記事1本を添削いたします。',
                'is_active' => true,
                'sort_order' => 12,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SNS投稿10件提案',
                'points_cost' => 1500,
                'description' => 'SNS投稿のアイデアを10件提案いたします。',
                'is_active' => true,
                'sort_order' => 13,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'SEO記事構成作成',
                'points_cost' => 2000,
                'description' => 'SEO記事の構成を作成いたします。',
                'is_active' => true,
                'sort_order' => 14,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // デザイン
            [
                'name' => 'バナー1枚制作',
                'points_cost' => 500,
                'description' => 'バナー1枚を制作いたします。',
                'is_active' => true,
                'sort_order' => 15,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'アイコン制作',
                'points_cost' => 800,
                'description' => 'アイコンを制作いたします。',
                'is_active' => true,
                'sort_order' => 16,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'OGP画像制作',
                'points_cost' => 1000,
                'description' => 'OGP画像を制作いたします。',
                'is_active' => true,
                'sort_order' => 17,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'キャンペーンバナー一式',
                'points_cost' => 2000,
                'description' => 'キャンペーンバナーを制作いたします。',
                'is_active' => true,
                'sort_order' => 18,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Webサイト改善
            [
                'name' => 'ページ改善提案',
                'points_cost' => 1000,
                'description' => 'サイトの特定ページの改善点を提案いたします。',
                'is_active' => true,
                'sort_order' => 19,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'お問い合わせ改善提案',
                'points_cost' => 1500,
                'description' => 'お問い合わせフォームの改善点を提案いたします。',
                'is_active' => true,
                'sort_order' => 20,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '追加ページ制作',
                'points_cost' => 2000,
                'description' => '追加ページを制作いたします。',
                'is_active' => true,
                'sort_order' => 21,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ランディングページ改善',
                'points_cost' => 2500,
                'description' => 'ランディングページの改善点を提案いたします。',
                'is_active' => true,
                'sort_order' => 22,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // システム保守
            [
                'name' => '軽微な修正1件',
                'points_cost' => 500,
                'description' => '軽微な修正を1件対応いたします。',
                'is_active' => true,
                'sort_order' => 23,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '機能改善相談',
                'points_cost' => 1000,
                'description' => '機能改善に関する相談を承ります。',
                'is_active' => true,
                'sort_order' => 24,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '小規模機能追加',
                'points_cost' => 2000,
                'description' => '小規模な機能追加を対応いたします。',
                'is_active' => true,
                'sort_order' => 25,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'API接続相談',
                'points_cost' => 3000,
                'description' => 'API接続に関する相談を承ります。',
                'is_active' => true,
                'sort_order' => 26,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // 教育・サポート
            [
                'name' => '操作説明30分',
                'points_cost' => 300,
                'description' => '操作方法を30分間ご説明いたします。',
                'is_active' => true,
                'sort_order' => 27,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '操作研修60分',
                'points_cost' => 500,
                'description' => '操作方法を60分間ご説明いたします。',
                'is_active' => true,
                'sort_order' => 28,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '管理者向け研修',
                'points_cost' => 1000,
                'description' => '管理者向けの操作研修をオンラインで60分間ご説明いたします。',
                'is_active' => true,
                'sort_order' => 29,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'スタッフ向け研修',
                'points_cost' => 1500,
                'description' => 'スタッフ向けの操作研修をオンラインで60分間ご説明いたします。',
                'is_active' => true,
                'sort_order' => 30,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // AI活用
            [
                'name' => 'AI活用相談',
                'points_cost' => 500,
                'description' => 'AI活用に関する相談を承ります。',
                'is_active' => true,
                'sort_order' => 31,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ChatGPTプロンプト作成',
                'points_cost' => 1000,
                'description' => 'ChatGPT用のプロンプトを作成いたします。',
                'is_active' => true,
                'sort_order' => 32,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '業務改善アイデア提案',
                'points_cost' => 1500,
                'description' => '業務改善に関するアイデアを提案いたします。',
                'is_active' => true,
                'sort_order' => 33,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'AI導入相談',
                'points_cost' => 2000,
                'description' => 'AI導入に関する相談をオンラインで承ります。',
                'is_active' => true,
                'sort_order' => 34,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($pointCatalogItems as $pointCatalogItem) {
            PointCatalogItem::create($pointCatalogItem);
        }
    }
}
