<?php

namespace Database\Seeders;

use App\Models\ScheduleException;
use Illuminate\Database\Seeder;

class ScheduleExceptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $exceptions = [
            // 2022年5月13日以降から
            [
                'exception_date' => '2022-08-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-08-15',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-08-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2022-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2022-12-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            // 2023年
            [
                'exception_date' => '2023-01-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2023-08-14',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2023-08-15',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2023-08-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2023-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2023-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            // 2024年
            [
                'exception_date' => '2024-01-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2024-01-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2024-08-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2024-08-14',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2024-08-15',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2024-08-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            // 2025年
            [
                'exception_date' => '2025-01-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2025-01-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2025-08-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2025-08-14',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2025-08-15',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2025-08-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            // 2026年
            [
                'exception_date' => '2026-01-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2026-01-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2026-08-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2026-08-14',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2026-08-15',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2026-08-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2026-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2026-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2026-12-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2027-01-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2027-08-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2027-08-14',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2027-08-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => 'お盆休業',
                'notes' => 'お盆のため休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2027-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2027-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2027-12-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2028-01-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
        ];

        foreach ($exceptions as $exception) {
            ScheduleException::updateOrCreate(
                ['exception_date' => $exception['exception_date']],
                $exception
            );
        }
    }
}
