<?php

namespace Database\Seeders;

use App\Models\ScheduleException;
use Illuminate\Database\Seeder;

class ScheduleExceptionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $exceptions = [
            // 2022年5月13日以降から
            [
                'exception_date' => '2022-05-27',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '引っ越し作業に伴い臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-05-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '引っ越し作業に伴い臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-05-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '引っ越し作業に伴い臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-09-24',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '技術研修のため臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-10-12',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-10-18',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-10-19',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-10-20',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-10-21',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2022-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2022-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            // 2023年
            [
                'exception_date' => '2023-01-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2023-01-04',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2023-01-05',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2023-03-28',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-03-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-04-11',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-04-12',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-04-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-04-14',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-04-19',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-04-20',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-04-21',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-05-10',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-05-11',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-06-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-06-14',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-06-15',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-06-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-09-26',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-09-27',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-09-28',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-09-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-04',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-05',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-06',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-11',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-12',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-17',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-18',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-19',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-10-20',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-11-27',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-11-28',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-11-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-11-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-12-01',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2023-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            // 2024年
            [
                'exception_date' => '2024-01-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2024-01-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2024-01-04',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2024-01-05',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-07',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-08',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-09',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-10',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-10',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-13',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-14',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-15',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-19',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-20',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-21',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-22',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-26',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-27',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-28',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-02-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-03-01',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-03-04',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-03-05',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-03-06',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-03-07',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-07-26',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-09-18',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-09-19',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-09-20',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-09-24',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-09-25',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-09-26',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-11-15',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-11-18',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-16',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-17',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-18',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-19',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-20',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-23',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-24',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-25',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-26',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-27',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2024-12-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            // 2025年
            [
                'exception_date' => '2025-01-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2025-01-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2025-01-06',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-01-07',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-01-08',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-01-09',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-01-10',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            // 2月から11月は後で追記
            [
                'exception_date' => '2025-12-17',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-18',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-19',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-20',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-22',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-23',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-24',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-25',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-26',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2025-12-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            // 2026年
            [
                'exception_date' => '2026-01-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2026-03-21',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2026-04-01',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2026-04-02',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2026-04-03',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            [
                'exception_date' => '2026-04-04',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '臨時休業のため、営業していません。',
            ],
            // 4/6 - 5/15は後で追記
            [
                'exception_date' => '2026-05-18',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-19',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-20',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-21',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-22',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-23',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '技術研修のため臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-25',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '技術研修のため臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-26',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '技術研修のため臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-27',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '臨時休業',
                'notes' => '技術研修のため臨時休業いたします。そのため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-28',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            [
                'exception_date' => '2026-05-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '委託業務休業',
                'notes' => '委託業務のため、営業していません。',
            ],
            // 6月から11月は後で追記
            [
                'exception_date' => '2026-12-29',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2026-12-30',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
            [
                'exception_date' => '2026-12-31',
                'is_open' => false,
                'open_time' => null,
                'close_time' => null,
                'break_start' => null,
                'break_end' => null,
                'reason' => '年末年始休業',
                'notes' => '年末年始のため、営業していません。',
            ],
        ];

        foreach ($exceptions as $exception) {
            ScheduleException::updateOrCreate(
                ['exception_date' => $exception['exception_date']],
                $exception
            );
        }
    }
}
