<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\ServicePlan;
use App\Models\Service;
use App\Models\Admin;

class ServicePlanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminId = Admin::first()->id;

        $websiteProduction = Service::where('slug', 'website-production')->first();
        $websiteMaintenance = Service::where('slug', 'website-maintenance')->first();
        $websiteContentManagement = Service::where('slug', 'website-content-management')->first();
        $landingPage = Service::where('slug', 'landing-page')->first();
        $landingPageMaintenance = Service::where('slug', 'landing-page-maintenance')->first();
        $ecommerceDevelopment = Service::where('slug', 'ecommerce-development')->first();
        $ecommerceMaintenance = Service::where('slug', 'ecommerce-maintenance')->first();
        $systemDevelopment = Service::where('slug', 'web-system-development')->first();
        $systemMaintenance = Service::where('slug', 'web-system-maintenance')->first();
        $saasDevelopment = Service::where('slug', 'saas-development')->first();
        $saasMaintenance = Service::where('slug', 'saas-maintenance')->first();
        $appDevelopment = Service::where('slug', 'app-development')->first();
        $appMaintenance = Service::where('slug', 'app-maintenance')->first();

        $servicePlans = [
            // ******************************
            // Webサイト制作のプラン
            // ******************************
            // ベーシックプラン、スタンダードプラン、プレミアムプラン
            [
                'name' => 'ベーシックプラン',
                'slug' => 'web-basic',
                'service_id' => $websiteProduction?->id,
                'description' => '小規模サイト向けの基本的な制作プラン',
                'details' => "5ページまでの構成で、企業や個人の基本情報を掲載するシンプルなプランです。\n\n含まれるもの：\n- レスポンシブデザイン\n- 基本的なSEO対策\n- お問い合わせフォーム",
                'base_price' => 300000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'スタンダードプラン',
                'slug' => 'web-standard',
                'service_id' => $websiteProduction?->id,
                'description' => '中規模サイト向けの充実した制作プラン',
                'details' => "10ページまでの構成で、企業や個人の魅力を十分に伝えられるプランです。\n\n含まれるもの：\n- レスポンシブデザイン\n- SEO対策（詳細設定）\n- お問い合わせフォーム\n- ブログ機能",
                'base_price' => 600000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 0,
                'max_revisions' => 3,
                'estimated_delivery_days' => 45,
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => '人気',
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'プレミアムプラン',
                'slug' => 'web-premium',
                'service_id' => $websiteProduction?->id,
                'description' => '大規模サイト向けの本格的な制作プラン',
                'details' => "20ページまでの構成で、多言語対応や高度な機能を含む本格的なプランです。\n\n含まれるもの：\n- 高度なデザイン\n- 詳細なSEO対策\n- 多言語対応（2言語）\n- CMS導入",
                'base_price' => 1200000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 60,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // オリジナルプラン
            [
                'name' => 'オリジナルプラン',
                'slug' => 'web-original',
                'service_id' => $websiteProduction?->id,
                'description' => 'お客様の要望に応じたカスタム制作プラン',
                'details' => "お客様のニーズに合わせて、ページ数や機能を自由にカスタマイズできるプランです。\n\n含まれるもの：\n- 完全オリジナルデザイン\n- 高度な機能追加\n- SEO対策\n- CMS導入",
                'base_price' => 2000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 150000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 4,
                'color' => '#F59E0B',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // Webサイト保守・運用のプラン
            // ******************************
            // ベーシックプラン、スタンダードプラン、プレミアムプラン、オリジナルプラン
            [
                'name' => 'ベーシックプラン',
                'slug' => 'web-maintenance-basic',
                'service_id' => $websiteMaintenance?->id,
                'description' => '小規模サイト向けの基本的な保守・運用プラン',
                'details' => "月額料金で、サイトの更新やトラブル対応を行う基本的な保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- サイトのバックアップ\n- トラブル対応",
                'base_price' => 8000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'スタンダードプラン',
                'slug' => 'web-maintenance-standard',
                'service_id' => $websiteMaintenance?->id,
                'description' => '中規模サイト向けの充実した保守・運用プラン',
                'details' => "月額料金で、サイトの更新やトラブル対応を行う充実した保守・運用プランです。\n\n含まれるもの：\n- 月2回の更新作業\n- サイトのバックアップ\n- トラブル対応\n- SEO対策の簡易チェック",
                'base_price' => 10000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 3,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'プレミアムプラン',
                'slug' => 'web-maintenance-premium',
                'service_id' => $websiteMaintenance?->id,
                'description' => '大規模サイト向けの本格的な保守・運用プラン',
                'details' => "月額料金で、サイトの更新やトラブル対応を行う本格的な保守・運用プランです。\n\n含まれるもの：\n- 月4回の更新作業\n- サイトのバックアップ\n- トラブル対応\n- SEO対策の詳細チェック\n- アクセス解析レポート",
                'base_price' => 12000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 5,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'オリジナルプラン',
                'slug' => 'web-maintenance-original',
                'service_id' => $websiteMaintenance?->id,
                'description' => 'お客様の要望に応じたカスタム保守・運用プラン',
                'details' => "お客様のニーズに合わせて、更新頻度や対応内容を自由にカスタマイズできる保守・運用プランです。\n\n含まれるもの：\n- 完全カスタマイズ対応\n- サイトのバックアップ\n- トラブル対応\n- SEO対策\n- アクセス解析レポート",
                'base_price' => 15000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 5,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 4,
                'color' => '#F59E0B',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // Webサイトコンテンツ運用のプラン
            // ******************************
            // 梅プラン(週1回月4回)、竹プラン(週2回月8回)、松プラン(週3回月12回)の記事作成
            [
                'name' => '梅プラン',
                'slug' => 'web-content-ume',
                'service_id' => $websiteContentManagement?->id,
                'description' => '週1回のコンテンツ更新を行う基本プラン',
                'details' => "月4回のコンテンツ更新を行う基本的な運用プランです。\n\n含まれるもの：\n- 記事作成（週1回）\n- 画像選定・編集\n- SEO対策の簡易チェック",
                'base_price' => 40000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '竹プラン',
                'slug' => 'web-content-take',
                'service_id' => $websiteContentManagement?->id,
                'description' => '週2回のコンテンツ更新を行う充実プラン',
                'details' => "月8回のコンテンツ更新を行う充実した運用プランです。\n\n含まれるもの：\n- 記事作成（週2回）\n- 画像選定・編集\n- SEO対策の詳細チェック",
                'base_price' => 70000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 3,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '松プラン',
                'slug' => 'web-content-matsu',
                'service_id' => $websiteContentManagement?->id,
                'description' => '週3回のコンテンツ更新を行う本格プラン',
                'details' => "月12回のコンテンツ更新を行う本格的な運用プランです。\n\n含まれるもの：\n- 記事作成（週3回）\n- 画像選定・編集\n- SEO対策の詳細チェック\n- アクセス解析レポート",
                'base_price' => 100000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 5,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // LP制作のプラン
            // ******************************
            // ベーシックプラン、スタンダードプラン、プレミアムプラン
            [
                'name' => 'ベーシックプラン',
                'slug' => 'lp-basic',
                'service_id' => $landingPage?->id,
                'description' => '小規模LP向けの基本的な制作プラン',
                'details' => "1ページ構成で、商品やサービスの基本情報を掲載するシンプルなプランです。\n\n含まれるもの：\n- レスポンシブデザイン\n- 基本的なSEO対策\n- お問い合わせフォーム",
                'base_price' => 150000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 15,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'スタンダードプラン',
                'slug' => 'lp-standard',
                'service_id' => $landingPage?->id,
                'description' => '中規模LP向けの充実した制作プラン',
                'details' => "2ページ構成で、商品やサービスの魅力を十分に伝えられるプランです。\n\n含まれるもの：\n- レスポンシブデザイン\n- SEO対策（詳細設定）\n- お問い合わせフォーム\n- 簡易的なアニメーション",
                'base_price' => 300000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 0,
                'max_revisions' => 3,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => '人気',
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'プレミアムプラン',
                'slug' => 'lp-premium',
                'service_id' => $landingPage?->id,
                'description' => '大規模LP向けの本格的な制作プラン',
                'details' => "3ページ構成で、多言語対応や高度な機能を含む本格的なプランです。\n\n含まれるもの：\n- 高度なデザイン\n- 詳細なSEO対策\n- 多言語対応（2言語）\n- アニメーション・インタラクション",
                'base_price' => 600000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 50000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 45,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // LP保守・運用のプラン
            // ******************************
            // ベーシックプラン、スタンダードプラン、プレミアムプラン
            [
                'name' => 'ベーシックプラン',
                'slug' => 'lp-maintenance-basic',
                'service_id' => $landingPageMaintenance?->id,
                'description' => '小規模LP向けの基本的な保守・運用プラン',
                'details' => "月額料金で、LPの更新やトラブル対応を行う基本的な保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- LPのバックアップ\n- トラブル対応",
                'base_price' => 5000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'スタンダードプラン',
                'slug' => 'lp-maintenance-standard',
                'service_id' => $landingPageMaintenance?->id,
                'description' => '中規模LP向けの充実した保守・運用プラン',
                'details' => "月額料金で、LPの更新やトラブル対応を行う充実した保守・運用プランです。\n\n含まれるもの：\n- 月2回の更新作業\n- LPのバックアップ\n- トラブル対応\n- SEO対策の簡易チェック",
                'base_price' => 8000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 3,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'プレミアムプラン',
                'slug' => 'lp-maintenance-premium',
                'service_id' => $landingPageMaintenance?->id,
                'description' => '大規模LP向けの本格的な保守・運用プラン',
                'details' => "月額料金で、LPの更新やトラブル対応を行う本格的な保守・運用プランです。\n\n含まれるもの：\n- 月4回の更新作業\n- LPのバックアップ\n- トラブル対応\n- SEO対策の詳細チェック\n- アクセス解析レポート",
                'base_price' => 12000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 5,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // ECサイト制作のプラン
            // ******************************
            // Shopifyプラン、WooCommerceプラン、オリジナルプラン
            [
                'name' => 'Shopifyプラン',
                'slug' => 'ec-shopify',
                'service_id' => $ecommerceDevelopment?->id,
                'description' => 'Shopifyを使用したECサイト制作プラン',
                'details' => "Shopifyを使用して、商品登録や決済機能を備えたECサイトを構築するプランです。\n\n含まれるもの：\n- Shopifyテーマのカスタマイズ\n- 商品登録（最大50点）\n- 決済機能の設定\n- 基本的なSEO対策",
                'base_price' => 500000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 50000,
                'max_revisions' => 3,
                'estimated_delivery_days' => 45,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#F59E0B',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'WooCommerceプラン',
                'slug' => 'ec-woocommerce',
                'service_id' => $ecommerceDevelopment?->id,
                'description' => 'WooCommerceを使用したECサイト制作プラン',
                'details' => "WooCommerceを使用して、商品登録や決済機能を備えたECサイトを構築するプランです。\n\n含まれるもの：\n- WooCommerceテーマのカスタマイズ\n- 商品登録（最大50点）\n- 決済機能の設定\n- 基本的なSEO対策",
                'base_price' => 600000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 50000,
                'max_revisions' => 3,
                'estimated_delivery_days' => 45,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'オリジナルプラン',
                'slug' => 'ec-original',
                'service_id' => $ecommerceDevelopment?->id,
                'description' => 'お客様の要望に応じたカスタムECサイト制作プラン',
                'details' => "お客様のニーズに合わせて、ページ数や機能を自由にカスタマイズできるECサイト制作プランです。\n\n含まれるもの：\n- 完全オリジナルデザイン\n- 高度な機能追加\n- SEO対策\n- CMS導入",
                'base_price' => 2000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 60,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // ECサイト保守・運用のプラン
            // ******************************
            // Shopifyプラン、WooCommerceプラン、オリジナルプラン
            [
                'name' => 'Shopify保守プラン',
                'slug' => 'ec-shopify-maintenance',
                'service_id' => $ecommerceMaintenance?->id,
                'description' => 'Shopifyを使用したECサイトの保守・運用プラン',
                'details' => "月額料金で、Shopifyを使用したECサイトの更新やトラブル対応を行う保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- サイトのバックアップ\n- トラブル対応",
                'base_price' => 10000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#F59E0B',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'WooCommerce保守プラン',
                'slug' => 'ec-woocommerce-maintenance',
                'service_id' => $ecommerceMaintenance?->id,
                'description' => 'WooCommerceを使用したECサイトの保守・運用プラン',
                'details' => "月額料金で、WooCommerceを使用したECサイトの更新やトラブル対応を行う保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- サイトのバックアップ\n- トラブル対応",
                'base_price' => 12000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'オリジナル保守プラン',
                'slug' => 'ec-original-maintenance',
                'service_id' => $ecommerceMaintenance?->id,
                'description' => 'お客様の要望に応じたカスタムECサイトの保守・運用プラン',
                'details' => "月額料金で、お客様のニーズに合わせて、更新頻度や対応内容を自由にカスタマイズできるECサイトの保守・運用プランです。\n\n含まれるもの：\n- 完全カスタマイズ対応\n- サイトのバックアップ\n- トラブル対応\n- SEO対策\n- アクセス解析レポート",
                'base_price' => 15000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 5,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // Webシステム開発のプラン
            // ******************************
            // 業務管理システム、顧客管理システム、予約システム、勤怠管理システム、
            [
                'name' => '業務管理システム開発プラン',
                'slug' => 'web-system-business-management',
                'service_id' => $systemDevelopment?->id,
                'description' => '業務管理システムの開発プラン',
                'details' => "企業の業務効率化を目的とした業務管理システムを開発するプランです。\n\n含まれるもの：\n- 要件定義\n- システム設計\n- 開発・テスト\n- 導入サポート",
                'base_price' => 2000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '顧客管理システム開発プラン',
                'slug' => 'web-system-customer-management',
                'service_id' => $systemDevelopment?->id,
                'description' => '顧客管理システムの開発プラン',
                'details' => "顧客情報の一元管理を目的とした顧客管理システムを開発するプランです。\n\n含まれるもの：\n- 要件定義\n- システム設計\n- 開発・テスト\n- 導入サポート",
                'base_price' => 2500000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '予約システム開発プラン',
                'slug' => 'web-system-reservation',
                'service_id' => $systemDevelopment?->id,
                'description' => '予約システムの開発プラン',
                'details' => "オンライン予約の効率化を目的とした予約システムを開発するプランです。\n\n含まれるもの：\n- 要件定義\n- システム設計\n- 開発・テスト\n- 導入サポート",
                'base_price' => 3000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '勤怠管理システム開発プラン',
                'slug' => 'web-system-attendance-management',
                'service_id' => $systemDevelopment?->id,
                'description' => '勤怠管理システムの開発プラン',
                'details' => "従業員の勤怠管理を効率化するための勤怠管理システムを開発するプランです。\n\n含まれるもの：\n- 要件定義\n- システム設計\n- 開発・テスト\n- 導入サポート",
                'base_price' => 3500000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 4,
                'color' => '#F59E0B',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'POSシステム開発プラン',
                'slug' => 'web-system-pos',
                'service_id' => $systemDevelopment?->id,
                'description' => 'POSシステムの開発プラン',
                'details' => "店舗の販売管理を効率化するためのPOSシステムを開発するプランです。\n\n含まれるもの：\n- 要件定義\n- システム設計\n- 開発・テスト\n- 導入サポート",
                'base_price' => 4000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 5,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '会計管理システム開発プラン',
                'slug' => 'web-system-accounting-management',
                'service_id' => $systemDevelopment?->id,
                'description' => '会計管理システムの開発プラン',
                'details' => "企業の財務管理を効率化するための会計管理システムを開発するプランです。\n\n含まれるもの：\n- 要件定義\n- システム設計\n- 開発・テスト\n- 導入サポート",
                'base_price' => 4500000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 6,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'オリジナルシステム開発プラン',
                'slug' => 'web-system-original',
                'service_id' => $systemDevelopment?->id,
                'description' => 'お客様の要望に応じたカスタムWebシステム開発プラン',
                'details' => "お客様のニーズに合わせて、業務フローや機能を自由にカスタマイズできるWebシステム開発プランです。\n\n含まれるもの：\n- 完全オリジナル設計\n- 高度な機能追加\n- SEO対策\n- CMS導入",
                'base_price' => 5000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 150000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 180,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 7,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // Webシステム保守・運用のプラン
            // ******************************
            // 業務管理システム、顧客管理システム、予約システム、勤怠管理システム、POSシステム、会計管理システム、オリジナルシステム
            [
                'name' => '業務管理システム保守プラン',
                'slug' => 'web-system-business-management-maintenance',
                'service_id' => $systemMaintenance?->id,
                'description' => '業務管理システムの保守・運用プラン',
                'details' => "月額料金で、業務管理システムの更新やトラブル対応を行う保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- システムのバックアップ\n- トラブル対応",
                'base_price' => 20000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '顧客管理システム保守プラン',
                'slug' => 'web-system-customer-management-maintenance',
                'service_id' => $systemMaintenance?->id,
                'description' => '顧客管理システムの保守・運用プラン',
                'details' => "月額料金で、顧客管理システムの更新やトラブル対応を行う保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- システムのバックアップ\n- トラブル対応",
                'base_price' => 25000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '予約システム保守プラン',
                'slug' => 'web-system-reservation-maintenance',
                'service_id' => $systemMaintenance?->id,
                'description' => '予約システムの保守・運用プラン',
                'details' => "月額料金で、予約システムの更新やトラブル対応を行う保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- システムのバックアップ\n- トラブル対応",
                'base_price' => 30000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '勤怠管理システム保守プラン',
                'slug' => 'web-system-attendance-management-maintenance',
                'service_id' => $systemMaintenance?->id,
                'description' => '勤怠管理システムの保守・運用プラン',
                'details' => "月額料金で、勤怠管理システムの更新やトラブル対応を行う保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- システムのバックアップ\n- トラブル対応",
                'base_price' => 35000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 4,
                'color' => '#F59E0B',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'POSシステム保守プラン',
                'slug' => 'web-system-pos-maintenance',
                'service_id' => $systemMaintenance?->id,
                'description' => 'POSシステムの保守・運用プラン',
                'details' => "月額料金で、POSシステムの更新やトラブル対応を行う保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- システムのバックアップ\n- トラブル対応",
                'base_price' => 40000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 5,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => '会計管理システム保守プラン',
                'slug' => 'web-system-accounting-management-maintenance',
                'service_id' => $systemMaintenance?->id,
                'description' => '会計管理システムの保守・運用プラン',
                'details' => "月額料金で、会計管理システムの更新やトラブル対応を行う保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- システムのバックアップ\n- トラブル対応",
                'base_price' => 45000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 6,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'オリジナルシステム保守プラン',
                'slug' => 'web-system-original-maintenance',
                'service_id' => $systemMaintenance?->id,
                'description' => 'お客様の要望に応じたカスタムWebシステムの保守・運用プラン',
                'details' => "月額料金で、お客様のニーズに合わせて、更新頻度や対応内容を自由にカスタマイズできるWebシステムの保守・運用プランです。\n\n含まれるもの：\n- 完全カスタマイズ対応\n- システムのバックアップ\n- トラブル対応\n- SEO対策\n- アクセス解析レポート",
                'base_price' => 50000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 7,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // SaaS開発のプラン
            // ******************************
            // ベーシックプラン、スタンダードプラン、プレミアムプラン
            [
                'name' => 'ベーシックプラン',
                'slug' => 'saas-basic',
                'service_id' => $saasDevelopment?->id,
                'description' => '小規模SaaS向けの基本的な開発プラン',
                'details' => "シンプルな機能を持つ小規模SaaSを開発する基本的なプランです。\n\n含まれるもの：\n- 基本的なUI/UXデザイン\n- 主要機能の実装\n- テスト・デバッグ",
                'base_price' => 2000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 3,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'スタンダードプラン',
                'slug' => 'saas-standard',
                'service_id' => $saasDevelopment?->id,
                'description' => '中規模SaaS向けの充実した開発プラン',
                'details' => "複数の機能を持つ中規模SaaSを開発する充実したプランです。\n\n含まれるもの：\n- UI/UXデザインのカスタマイズ\n- 複数機能の実装\n- テスト・デバッグ\n- 簡易的なAPI連携",
                'base_price' => 4000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 200000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 120,
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => '人気',
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'プレミアムプラン',
                'slug' => 'saas-premium',
                'service_id' => $saasDevelopment?->id,
                'description' => '大規模SaaS向けの本格的な開発プラン',
                'details' => "高度な機能を持つ大規模SaaSを開発する本格的なプランです。\n\n含まれるもの：\n- 高度なUI/UXデザイン\n- 複雑な機能の実装\n- テスト・デバッグ\n- API連携\n- パフォーマンス最適化",
                'base_price' => 8000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 400000,
                'max_revisions' => 10,
                'estimated_delivery_days' => 180,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // SaaS保守・運用のプラン
            // ******************************
            // ベーシックプラン、スタンダードプラン、プレミアムプラン
            [
                'name' => 'ベーシックプラン',
                'slug' => 'saas-maintenance-basic',
                'service_id' => $saasMaintenance?->id,
                'description' => '小規模SaaS向けの基本的な保守・運用プラン',
                'details' => "月額料金で、SaaSの更新やトラブル対応を行う基本的な保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- SaaSのバックアップ\n- トラブル対応",
                'base_price' => 20000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'スタンダードプラン',
                'slug' => 'saas-maintenance-standard',
                'service_id' => $saasMaintenance?->id,
                'description' => '中規模SaaS向けの充実した保守・運用プラン',
                'details' => "月額料金で、SaaSの更新やトラブル対応を行う充実した保守・運用プランです。\n\n含まれるもの：\n- 月2回の更新作業\n- SaaSのバックアップ\n- トラブル対応\n- 簡易的なAPI連携",
                'base_price' => 40000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 3,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => '人気',
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'プレミアムプラン',
                'slug' => 'saas-maintenance-premium',
                'service_id' => $saasMaintenance?->id,
                'description' => '大規模SaaS向けの本格的な保守・運用プラン',
                'details' => "月額料金で、SaaSの更新やトラブル対応を行う本格的な保守・運用プランです。\n\n含まれるもの：\n- 月4回の更新作業\n- SaaSのバックアップ\n- トラブル対応\n- API連携\n- パフォーマンス最適化",
                'base_price' => 80000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 5,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // アプリ開発のプラン
            // ******************************
            // ベーシックプラン、スタンダードプラン、プレミアムプラン
            [
                'name' => 'ベーシックプラン',
                'slug' => 'app-basic',
                'service_id' => $appDevelopment?->id,
                'description' => '小規模アプリ向けの基本的な開発プラン',
                'details' => "シンプルな機能を持つ小規模アプリを開発する基本的なプランです。\n\n含まれるもの：\n- 基本的なUI/UXデザイン\n- 主要機能の実装\n- テスト・デバッグ",
                'base_price' => 1000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 50000,
                'max_revisions' => 3,
                'estimated_delivery_days' => 60,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'スタンダードプラン',
                'slug' => 'app-standard',
                'service_id' => $appDevelopment?->id,
                'description' => '中規模アプリ向けの充実した開発プラン',
                'details' => "複数の機能を持つ中規模アプリを開発する充実したプランです。\n\n含まれるもの：\n- UI/UXデザインのカスタマイズ\n- 複数機能の実装\n- テスト・デバッグ\n- 簡易的なAPI連携",
                'base_price' => 2000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 100000,
                'max_revisions' => 5,
                'estimated_delivery_days' => 90,
                'status' => 'active',
                'is_featured' => true,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => '人気',
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'プレミアムプラン',
                'slug' => 'app-premium',
                'service_id' => $appDevelopment?->id,
                'description' => '大規模アプリ向けの本格的な開発プラン',
                'details' => "高度な機能を持つ大規模アプリを開発する本格的なプランです。\n\n含まれるもの：\n- 高度なUI/UXデザイン\n- 複雑な機能の実装\n- テスト・デバッグ\n- API連携\n- パフォーマンス最適化",
                'base_price' => 5000000,
                'discount_amount' => 0,
                'billing_cycle' => 'one_time',
                'setup_fee' => 200000,
                'max_revisions' => 10,
                'estimated_delivery_days' => 180,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            // ******************************
            // アプリ保守・運用のプラン
            // ******************************
            [
                'name' => 'ベーシックプラン',
                'slug' => 'app-maintenance-basic',
                'service_id' => $appMaintenance?->id,
                'description' => '小規模アプリ向けの基本的な保守・運用プラン',
                'details' => "月額料金で、アプリの更新やトラブル対応を行う基本的な保守・運用プランです。\n\n含まれるもの：\n- 月1回の更新作業\n- アプリのバックアップ\n- トラブル対応",
                'base_price' => 10000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 2,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 1,
                'color' => '#3B82F6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'スタンダードプラン',
                'slug' => 'app-maintenance-standard',
                'service_id' => $appMaintenance?->id,
                'description' => '中規模アプリ向けの充実した保守・運用プラン',
                'details' => "月額料金で、アプリの更新やトラブル対応を行う充実した保守・運用プランです。\n\n含まれるもの：\n- 月2回の更新作業\n- アプリのバックアップ\n- トラブル対応\n- 簡易的な機能追加",
                'base_price' => 20000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 3,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 2,
                'color' => '#10B981',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
            [
                'name' => 'プレミアムプラン',
                'slug' => 'app-maintenance-premium',
                'service_id' => $appMaintenance?->id,
                'description' => '大規模アプリ向けの本格的な保守・運用プラン',
                'details' => "月額料金で、アプリの更新やトラブル対応を行う本格的な保守・運用プランです。\n\n含まれるもの：\n- 月4回の更新作業\n- アプリのバックアップ\n- トラブル対応\n- 機能追加\n- パフォーマンス最適化",
                'base_price' => 50000,
                'discount_amount' => 0,
                'billing_cycle' => 'monthly',
                'setup_fee' => 0,
                'max_revisions' => 5,
                'estimated_delivery_days' => 30,
                'status' => 'active',
                'is_featured' => false,
                'sort_order' => 3,
                'color' => '#8B5CF6',
                'badge_text' => null,
                'icon' => null,
                'created_by' => $adminId,
                'updated_by' => $adminId,
            ],
        ];

        foreach ($servicePlans as $servicePlan) {
            // service_id が null でない場合のみ作成
            if (!empty($servicePlan['service_id'])) {
                ServicePlan::firstOrCreate(
                    ['slug' => $servicePlan['slug']],
                    $servicePlan
                );
            }
        }
    }
}
